package com.gandalf.lottery.dao;

import java.util.List;

import com.gandalf.framework.ibatis.PaginationQueryList;
import com.gandalf.lottery.dao.entity.OpPermission;
import com.gandalf.lottery.dao.entity.OpPermissionExample;

public interface OpPermissionDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    void insert(OpPermission record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    int updateByPrimaryKey(OpPermission record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    int updateByPrimaryKeySelective(OpPermission record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    List selectByExample(OpPermissionExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    OpPermission selectByPrimaryKey(Long permissionId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    int deleteByExample(OpPermissionExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    int deleteByPrimaryKey(Long permissionId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    int countByExample(OpPermissionExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    int updateByExampleSelective(OpPermission record, OpPermissionExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission
     * 
     * @abatorgenerated
     */
    int updateByExample(OpPermission record, OpPermissionExample example);

    PaginationQueryList<OpPermission> selectByPagination(OpPermissionExample example);
}
