package com.gandalf.lottery.dao;

import com.gandalf.lottery.dao.entity.OpPermissionGroup;
import com.gandalf.lottery.dao.entity.OpPermissionGroupExample;
import java.util.List;

public interface OpPermissionGroupDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    void insert(OpPermissionGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    int updateByPrimaryKey(OpPermissionGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    int updateByPrimaryKeySelective(OpPermissionGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    List selectByExample(OpPermissionGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    OpPermissionGroup selectByPrimaryKey(Long permissionGroupId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    int deleteByExample(OpPermissionGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    int deleteByPrimaryKey(Long permissionGroupId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    int countByExample(OpPermissionGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    int updateByExampleSelective(OpPermissionGroup record, OpPermissionGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    int updateByExample(OpPermissionGroup record, OpPermissionGroupExample example);
}