package com.gandalf.lottery.dao;

import com.gandalf.lottery.dao.entity.OpPermissionURI;
import com.gandalf.lottery.dao.entity.OpPermissionURIExample;
import java.util.List;

public interface OpPermissionURIDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_uri
     *
     * @abatorgenerated
     */
    void insert(OpPermissionURI record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_uri
     *
     * @abatorgenerated
     */
    List selectByExample(OpPermissionURIExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_uri
     *
     * @abatorgenerated
     */
    int deleteByExample(OpPermissionURIExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_uri
     *
     * @abatorgenerated
     */
    int countByExample(OpPermissionURIExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_uri
     *
     * @abatorgenerated
     */
    int updateByExampleSelective(OpPermissionURI record, OpPermissionURIExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_uri
     *
     * @abatorgenerated
     */
    int updateByExample(OpPermissionURI record, OpPermissionURIExample example);
}