package com.gandalf.lottery.dao;

import com.gandalf.lottery.dao.entity.OpPermissionResource;
import com.gandalf.lottery.dao.entity.OpPermissionResourceExample;
import java.util.List;

public interface OpPermissionResourceDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_resource
     *
     * @abatorgenerated
     */
    void insert(OpPermissionResource record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_resource
     *
     * @abatorgenerated
     */
    List selectByExample(OpPermissionResourceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_resource
     *
     * @abatorgenerated
     */
    int deleteByExample(OpPermissionResourceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_resource
     *
     * @abatorgenerated
     */
    int countByExample(OpPermissionResourceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_resource
     *
     * @abatorgenerated
     */
    int updateByExampleSelective(OpPermissionResource record, OpPermissionResourceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_resource
     *
     * @abatorgenerated
     */
    int updateByExample(OpPermissionResource record, OpPermissionResourceExample example);
}