package com.gandalf.lottery.dao;

import java.util.List;

import com.gandalf.framework.ibatis.PaginationQueryList;
import com.gandalf.lottery.dao.entity.OpResource;
import com.gandalf.lottery.dao.entity.OpResourceExample;

public interface OpResourceDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    void insert(OpResource record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    int updateByPrimaryKey(OpResource record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    int updateByPrimaryKeySelective(OpResource record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    List selectByExample(OpResourceExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    OpResource selectByPrimaryKey(Long resourceId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    int deleteByExample(OpResourceExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    int deleteByPrimaryKey(Long resourceId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    int countByExample(OpResourceExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    int updateByExampleSelective(OpResource record, OpResourceExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    int updateByExample(OpResource record, OpResourceExample example);

    PaginationQueryList<OpResource> selectByPagination(OpResourceExample example);
}
