package com.gandalf.lottery.dao;

import java.util.List;

import com.gandalf.framework.ibatis.PaginationQueryList;
import com.gandalf.lottery.dao.entity.OpRole;
import com.gandalf.lottery.dao.entity.OpRoleExample;

public interface OpRoleDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    void insert(OpRole record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    int updateByPrimaryKey(OpRole record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    int updateByPrimaryKeySelective(OpRole record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    List selectByExample(OpRoleExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    OpRole selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    int deleteByExample(OpRoleExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    int countByExample(OpRoleExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    int updateByExampleSelective(OpRole record, OpRoleExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    int updateByExample(OpRole record, OpRoleExample example);

    PaginationQueryList<OpRole> selectByPagination(OpRoleExample example);
}
