package com.gandalf.lottery.dao;

import com.gandalf.lottery.dao.entity.OpRolePermission;
import com.gandalf.lottery.dao.entity.OpRolePermissionExample;
import java.util.List;

public interface OpRolePermissionDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_role_permission
     *
     * @abatorgenerated
     */
    void insert(OpRolePermission record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_role_permission
     *
     * @abatorgenerated
     */
    List selectByExample(OpRolePermissionExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_role_permission
     *
     * @abatorgenerated
     */
    int deleteByExample(OpRolePermissionExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_role_permission
     *
     * @abatorgenerated
     */
    int countByExample(OpRolePermissionExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_role_permission
     *
     * @abatorgenerated
     */
    int updateByExampleSelective(OpRolePermission record, OpRolePermissionExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_role_permission
     *
     * @abatorgenerated
     */
    int updateByExample(OpRolePermission record, OpRolePermissionExample example);
}