package com.gandalf.lottery.dao.entity;


public class OpPermission {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * op_permission.permission_id
     * 
     * @abatorgenerated
     */
    private Long    permissionId;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * op_permission.permission_group_id
     * 
     * @abatorgenerated
     */
    private Long    permissionGroupId;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * op_permission.permission_name
     * 
     * @abatorgenerated
     */
    private String  permissionName;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * op_permission.menu_resource_id
     * 
     * @abatorgenerated
     */
    private Long    menuResourceId;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * op_permission.order_num
     * 
     * @abatorgenerated
     */
    private Integer orderNum;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * op_permission.permission_id
     * 
     * @return the value of op_permission.permission_id
     * @abatorgenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * op_permission.permission_id
     * 
     * @param permissionId the value for op_permission.permission_id
     * @abatorgenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * op_permission.permission_group_id
     * 
     * @return the value of op_permission.permission_group_id
     * @abatorgenerated
     */
    public Long getPermissionGroupId() {
        return permissionGroupId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * op_permission.permission_group_id
     * 
     * @param permissionGroupId the value for op_permission.permission_group_id
     * @abatorgenerated
     */
    public void setPermissionGroupId(Long permissionGroupId) {
        this.permissionGroupId = permissionGroupId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * op_permission.permission_name
     * 
     * @return the value of op_permission.permission_name
     * @abatorgenerated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * op_permission.permission_name
     * 
     * @param permissionName the value for op_permission.permission_name
     * @abatorgenerated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * op_permission.menu_resource_id
     * 
     * @return the value of op_permission.menu_resource_id
     * @abatorgenerated
     */
    public Long getMenuResourceId() {
        return menuResourceId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * op_permission.menu_resource_id
     * 
     * @param menuResourceId the value for op_permission.menu_resource_id
     * @abatorgenerated
     */
    public void setMenuResourceId(Long menuResourceId) {
        this.menuResourceId = menuResourceId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * op_permission.order_num
     * 
     * @return the value of op_permission.order_num
     * @abatorgenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * op_permission.order_num
     * 
     * @param orderNum the value for op_permission.order_num
     * @abatorgenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}
