package com.gandalf.lottery.dao.entity;

public class OpPermissionResource {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_permission_resource.permission_id
     *
     * @abatorgenerated
     */
    private Long permissionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_permission_resource.resource_id
     *
     * @abatorgenerated
     */
    private Long resourceId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_permission_resource.permission_id
     *
     * @return the value of op_permission_resource.permission_id
     *
     * @abatorgenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_permission_resource.permission_id
     *
     * @param permissionId the value for op_permission_resource.permission_id
     *
     * @abatorgenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_permission_resource.resource_id
     *
     * @return the value of op_permission_resource.resource_id
     *
     * @abatorgenerated
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_permission_resource.resource_id
     *
     * @param resourceId the value for op_permission_resource.resource_id
     *
     * @abatorgenerated
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }
}