package com.gandalf.lottery.dao.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OpPermissionGroupExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public OpPermissionGroupExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    protected OpPermissionGroupExample(OpPermissionGroupExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table op_permission_group
     *
     * @abatorgenerated
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andPermissionGroupIdIsNull() {
            addCriterion("permission_group_id is null");
            return this;
        }

        public Criteria andPermissionGroupIdIsNotNull() {
            addCriterion("permission_group_id is not null");
            return this;
        }

        public Criteria andPermissionGroupIdEqualTo(Long value) {
            addCriterion("permission_group_id =", value, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdNotEqualTo(Long value) {
            addCriterion("permission_group_id <>", value, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdGreaterThan(Long value) {
            addCriterion("permission_group_id >", value, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("permission_group_id >=", value, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdLessThan(Long value) {
            addCriterion("permission_group_id <", value, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("permission_group_id <=", value, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdIn(List values) {
            addCriterion("permission_group_id in", values, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdNotIn(List values) {
            addCriterion("permission_group_id not in", values, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdBetween(Long value1, Long value2) {
            addCriterion("permission_group_id between", value1, value2, "permissionGroupId");
            return this;
        }

        public Criteria andPermissionGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("permission_group_id not between", value1, value2, "permissionGroupId");
            return this;
        }

        public Criteria andGroupNameIsNull() {
            addCriterion("group_name is null");
            return this;
        }

        public Criteria andGroupNameIsNotNull() {
            addCriterion("group_name is not null");
            return this;
        }

        public Criteria andGroupNameEqualTo(String value) {
            addCriterion("group_name =", value, "groupName");
            return this;
        }

        public Criteria andGroupNameNotEqualTo(String value) {
            addCriterion("group_name <>", value, "groupName");
            return this;
        }

        public Criteria andGroupNameGreaterThan(String value) {
            addCriterion("group_name >", value, "groupName");
            return this;
        }

        public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("group_name >=", value, "groupName");
            return this;
        }

        public Criteria andGroupNameLessThan(String value) {
            addCriterion("group_name <", value, "groupName");
            return this;
        }

        public Criteria andGroupNameLessThanOrEqualTo(String value) {
            addCriterion("group_name <=", value, "groupName");
            return this;
        }

        public Criteria andGroupNameLike(String value) {
            addCriterion("group_name like", value, "groupName");
            return this;
        }

        public Criteria andGroupNameNotLike(String value) {
            addCriterion("group_name not like", value, "groupName");
            return this;
        }

        public Criteria andGroupNameIn(List values) {
            addCriterion("group_name in", values, "groupName");
            return this;
        }

        public Criteria andGroupNameNotIn(List values) {
            addCriterion("group_name not in", values, "groupName");
            return this;
        }

        public Criteria andGroupNameBetween(String value1, String value2) {
            addCriterion("group_name between", value1, value2, "groupName");
            return this;
        }

        public Criteria andGroupNameNotBetween(String value1, String value2) {
            addCriterion("group_name not between", value1, value2, "groupName");
            return this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("order_num is null");
            return this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("order_num is not null");
            return this;
        }

        public Criteria andOrderNumEqualTo(Integer value) {
            addCriterion("order_num =", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotEqualTo(Integer value) {
            addCriterion("order_num <>", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumGreaterThan(Integer value) {
            addCriterion("order_num >", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_num >=", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLessThan(Integer value) {
            addCriterion("order_num <", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(Integer value) {
            addCriterion("order_num <=", value, "orderNum");
            return this;
        }

        public Criteria andOrderNumIn(List values) {
            addCriterion("order_num in", values, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotIn(List values) {
            addCriterion("order_num not in", values, "orderNum");
            return this;
        }

        public Criteria andOrderNumBetween(Integer value1, Integer value2) {
            addCriterion("order_num between", value1, value2, "orderNum");
            return this;
        }

        public Criteria andOrderNumNotBetween(Integer value1, Integer value2) {
            addCriterion("order_num not between", value1, value2, "orderNum");
            return this;
        }
    }
}