package com.gandalf.lottery.dao.entity;

public class OpResource {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_resource.resource_id
     *
     * @abatorgenerated
     */
    private Long resourceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_resource.resource_name
     *
     * @abatorgenerated
     */
    private String resourceName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_resource.resource_uri
     *
     * @abatorgenerated
     */
    private String resourceURI;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_resource.resource_id
     *
     * @return the value of op_resource.resource_id
     *
     * @abatorgenerated
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_resource.resource_id
     *
     * @param resourceId the value for op_resource.resource_id
     *
     * @abatorgenerated
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_resource.resource_name
     *
     * @return the value of op_resource.resource_name
     *
     * @abatorgenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_resource.resource_name
     *
     * @param resourceName the value for op_resource.resource_name
     *
     * @abatorgenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_resource.resource_uri
     *
     * @return the value of op_resource.resource_uri
     *
     * @abatorgenerated
     */
    public String getResourceURI() {
        return resourceURI;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_resource.resource_uri
     *
     * @param resourceURI the value for op_resource.resource_uri
     *
     * @abatorgenerated
     */
    public void setResourceURI(String resourceURI) {
        this.resourceURI = resourceURI;
    }
}