package com.gandalf.lottery.dao.entity;

public class OpRolePermission {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_role_permission.role_id
     *
     * @abatorgenerated
     */
    private Long roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_role_permission.permission_id
     *
     * @abatorgenerated
     */
    private Long permissionId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_role_permission.role_id
     *
     * @return the value of op_role_permission.role_id
     *
     * @abatorgenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_role_permission.role_id
     *
     * @param roleId the value for op_role_permission.role_id
     *
     * @abatorgenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_role_permission.permission_id
     *
     * @return the value of op_role_permission.permission_id
     *
     * @abatorgenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_role_permission.permission_id
     *
     * @param permissionId the value for op_role_permission.permission_id
     *
     * @abatorgenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}