package com.gandalf.lottery.dao.entity;

public class OpRole {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_role.role_id
     *
     * @abatorgenerated
     */
    private Long roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_role.role_name
     *
     * @abatorgenerated
     */
    private String roleName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_role.role_desc
     *
     * @abatorgenerated
     */
    private String roleDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_role.role_alias
     *
     * @abatorgenerated
     */
    private String roleAlias;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_role.role_id
     *
     * @return the value of op_role.role_id
     *
     * @abatorgenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_role.role_id
     *
     * @param roleId the value for op_role.role_id
     *
     * @abatorgenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_role.role_name
     *
     * @return the value of op_role.role_name
     *
     * @abatorgenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_role.role_name
     *
     * @param roleName the value for op_role.role_name
     *
     * @abatorgenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_role.role_desc
     *
     * @return the value of op_role.role_desc
     *
     * @abatorgenerated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_role.role_desc
     *
     * @param roleDesc the value for op_role.role_desc
     *
     * @abatorgenerated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_role.role_alias
     *
     * @return the value of op_role.role_alias
     *
     * @abatorgenerated
     */
    public String getRoleAlias() {
        return roleAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_role.role_alias
     *
     * @param roleAlias the value for op_role.role_alias
     *
     * @abatorgenerated
     */
    public void setRoleAlias(String roleAlias) {
        this.roleAlias = roleAlias;
    }
}