package com.gandalf.lottery.dao.entity;

import com.gandalf.lottery.common.constant.EnableEnum;
import java.util.Date;

public class OpUser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.user_id
     *
     * @abatorgenerated
     */
    private Long userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.username
     *
     * @abatorgenerated
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.password
     *
     * @abatorgenerated
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.real_name
     *
     * @abatorgenerated
     */
    private String realName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.telephone
     *
     * @abatorgenerated
     */
    private String telephone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.email
     *
     * @abatorgenerated
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.department_id
     *
     * @abatorgenerated
     */
    private Long departmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.role_id
     *
     * @abatorgenerated
     */
    private Long roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.enable
     *
     * @abatorgenerated
     */
    private EnableEnum enable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.last_login_time
     *
     * @abatorgenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.last_login_ip
     *
     * @abatorgenerated
     */
    private String lastLoginIp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.gmt_create
     *
     * @abatorgenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column op_user.gmt_update
     *
     * @abatorgenerated
     */
    private Date gmtUpdate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.user_id
     *
     * @return the value of op_user.user_id
     *
     * @abatorgenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.user_id
     *
     * @param userId the value for op_user.user_id
     *
     * @abatorgenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.username
     *
     * @return the value of op_user.username
     *
     * @abatorgenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.username
     *
     * @param username the value for op_user.username
     *
     * @abatorgenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.password
     *
     * @return the value of op_user.password
     *
     * @abatorgenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.password
     *
     * @param password the value for op_user.password
     *
     * @abatorgenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.real_name
     *
     * @return the value of op_user.real_name
     *
     * @abatorgenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.real_name
     *
     * @param realName the value for op_user.real_name
     *
     * @abatorgenerated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.telephone
     *
     * @return the value of op_user.telephone
     *
     * @abatorgenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.telephone
     *
     * @param telephone the value for op_user.telephone
     *
     * @abatorgenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.email
     *
     * @return the value of op_user.email
     *
     * @abatorgenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.email
     *
     * @param email the value for op_user.email
     *
     * @abatorgenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.department_id
     *
     * @return the value of op_user.department_id
     *
     * @abatorgenerated
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.department_id
     *
     * @param departmentId the value for op_user.department_id
     *
     * @abatorgenerated
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.role_id
     *
     * @return the value of op_user.role_id
     *
     * @abatorgenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.role_id
     *
     * @param roleId the value for op_user.role_id
     *
     * @abatorgenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.enable
     *
     * @return the value of op_user.enable
     *
     * @abatorgenerated
     */
    public EnableEnum getEnable() {
        return enable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.enable
     *
     * @param enable the value for op_user.enable
     *
     * @abatorgenerated
     */
    public void setEnable(EnableEnum enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.last_login_time
     *
     * @return the value of op_user.last_login_time
     *
     * @abatorgenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.last_login_time
     *
     * @param lastLoginTime the value for op_user.last_login_time
     *
     * @abatorgenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.last_login_ip
     *
     * @return the value of op_user.last_login_ip
     *
     * @abatorgenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.last_login_ip
     *
     * @param lastLoginIp the value for op_user.last_login_ip
     *
     * @abatorgenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.gmt_create
     *
     * @return the value of op_user.gmt_create
     *
     * @abatorgenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.gmt_create
     *
     * @param gmtCreate the value for op_user.gmt_create
     *
     * @abatorgenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column op_user.gmt_update
     *
     * @return the value of op_user.gmt_update
     *
     * @abatorgenerated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column op_user.gmt_update
     *
     * @param gmtUpdate the value for op_user.gmt_update
     *
     * @abatorgenerated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}