package com.gandalf.lottery.dao.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.jdbc.support.incrementer.DataFieldMaxValueIncrementer;
import org.springframework.stereotype.Repository;

import com.gandalf.framework.ibatis.GandalfSqlMapClientDaoSupport;
import com.gandalf.lottery.dao.OpPermissionGroupDAO;
import com.gandalf.lottery.dao.entity.OpPermissionGroup;
import com.gandalf.lottery.dao.entity.OpPermissionGroupExample;

@Repository
public class OpPermissionGroupDAOImpl extends GandalfSqlMapClientDaoSupport implements OpPermissionGroupDAO {

    @Resource(name = "opPermissionGroupIncrementer")
    private DataFieldMaxValueIncrementer keyIncrementer;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public OpPermissionGroupDAOImpl() {
        super();
    }

    public void insert(OpPermissionGroup record) {
        if (record.getPermissionGroupId() == null) {
            record.setPermissionGroupId(keyIncrementer.nextLongValue());
        }
        getSqlMapClientTemplate().insert("op_permission_group.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public int updateByPrimaryKey(OpPermissionGroup record) {
        int rows = getSqlMapClientTemplate().update("op_permission_group.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(OpPermissionGroup record) {
        int rows = getSqlMapClientTemplate().update("op_permission_group.abatorgenerated_updateByPrimaryKeySelective",
                                                    record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public List selectByExample(OpPermissionGroupExample example) {
        List list = getSqlMapClientTemplate().queryForList("op_permission_group.abatorgenerated_selectByExample",
                                                           example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public OpPermissionGroup selectByPrimaryKey(Long permissionGroupId) {
        OpPermissionGroup key = new OpPermissionGroup();
        key.setPermissionGroupId(permissionGroupId);
        OpPermissionGroup record = (OpPermissionGroup) getSqlMapClientTemplate().queryForObject("op_permission_group.abatorgenerated_selectByPrimaryKey",
                                                                                                key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public int deleteByExample(OpPermissionGroupExample example) {
        int rows = getSqlMapClientTemplate().delete("op_permission_group.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long permissionGroupId) {
        OpPermissionGroup key = new OpPermissionGroup();
        key.setPermissionGroupId(permissionGroupId);
        int rows = getSqlMapClientTemplate().delete("op_permission_group.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public int countByExample(OpPermissionGroupExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("op_permission_group.abatorgenerated_countByExample",
                                                                           example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public int updateByExampleSelective(OpPermissionGroup record, OpPermissionGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_permission_group.abatorgenerated_updateByExampleSelective",
                                                    parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    public int updateByExample(OpPermissionGroup record, OpPermissionGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_permission_group.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table op_permission_group
     * 
     * @abatorgenerated
     */
    private static class UpdateByExampleParms extends OpPermissionGroupExample {

        private Object record;

        public UpdateByExampleParms(Object record, OpPermissionGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
