package com.gandalf.lottery.dao.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.gandalf.framework.ibatis.GandalfSqlMapClientDaoSupport;
import com.gandalf.lottery.dao.OpPermissionURIDAO;
import com.gandalf.lottery.dao.entity.OpPermissionURI;
import com.gandalf.lottery.dao.entity.OpPermissionURIExample;

@Repository
public class OpPermissionURIDAOImpl extends GandalfSqlMapClientDaoSupport implements OpPermissionURIDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    public OpPermissionURIDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    public void insert(OpPermissionURI record) {
        getSqlMapClientTemplate().insert("op_permission_uri.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    public List selectByExample(OpPermissionURIExample example) {
        List list = getSqlMapClientTemplate().queryForList("op_permission_uri.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    public int deleteByExample(OpPermissionURIExample example) {
        int rows = getSqlMapClientTemplate().delete("op_permission_uri.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    public int countByExample(OpPermissionURIExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("op_permission_uri.abatorgenerated_countByExample",
                                                                           example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    public int updateByExampleSelective(OpPermissionURI record, OpPermissionURIExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_permission_uri.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    public int updateByExample(OpPermissionURI record, OpPermissionURIExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_permission_uri.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table op_permission_uri
     * 
     * @abatorgenerated
     */
    private static class UpdateByExampleParms extends OpPermissionURIExample {

        private Object record;

        public UpdateByExampleParms(Object record, OpPermissionURIExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
