package com.gandalf.lottery.dao.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.gandalf.framework.ibatis.GandalfSqlMapClientDaoSupport;
import com.gandalf.lottery.dao.OpPermissionResourceDAO;
import com.gandalf.lottery.dao.entity.OpPermissionResource;
import com.gandalf.lottery.dao.entity.OpPermissionResourceExample;

@Repository
public class OpPermissionResourceDAOImpl extends GandalfSqlMapClientDaoSupport implements OpPermissionResourceDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    public OpPermissionResourceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    public void insert(OpPermissionResource record) {
        getSqlMapClientTemplate().insert("op_permission_resource.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    public List selectByExample(OpPermissionResourceExample example) {
        List list = getSqlMapClientTemplate().queryForList("op_permission_resource.abatorgenerated_selectByExample",
                                                           example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    public int deleteByExample(OpPermissionResourceExample example) {
        int rows = getSqlMapClientTemplate().delete("op_permission_resource.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    public int countByExample(OpPermissionResourceExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("op_permission_resource.abatorgenerated_countByExample",
                                                                           example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    public int updateByExampleSelective(OpPermissionResource record, OpPermissionResourceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_permission_resource.abatorgenerated_updateByExampleSelective",
                                                    parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    public int updateByExample(OpPermissionResource record, OpPermissionResourceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_permission_resource.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table
     * op_permission_resource
     * 
     * @abatorgenerated
     */
    private static class UpdateByExampleParms extends OpPermissionResourceExample {

        private Object record;

        public UpdateByExampleParms(Object record, OpPermissionResourceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
