package com.gandalf.lottery.dao.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.jdbc.support.incrementer.DataFieldMaxValueIncrementer;
import org.springframework.stereotype.Repository;

import com.gandalf.framework.ibatis.GandalfSqlMapClientDaoSupport;
import com.gandalf.framework.ibatis.PaginationQueryList;
import com.gandalf.lottery.dao.OpResourceDAO;
import com.gandalf.lottery.dao.entity.OpResource;
import com.gandalf.lottery.dao.entity.OpResourceExample;

@Repository
public class OpResourceDAOImpl extends GandalfSqlMapClientDaoSupport implements OpResourceDAO {

    @Resource(name = "opResourceIncrementer")
    private DataFieldMaxValueIncrementer keyIncrementer;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public OpResourceDAOImpl() {
        super();
    }

    public void insert(OpResource record) {
        if (record.getResourceId() == null) {
            record.setResourceId(keyIncrementer.nextLongValue());
        }
        getSqlMapClientTemplate().insert("op_resource.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public int updateByPrimaryKey(OpResource record) {
        int rows = getSqlMapClientTemplate().update("op_resource.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(OpResource record) {
        int rows = getSqlMapClientTemplate().update("op_resource.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public List selectByExample(OpResourceExample example) {
        List list = getSqlMapClientTemplate().queryForList("op_resource.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public OpResource selectByPrimaryKey(Long resourceId) {
        OpResource key = new OpResource();
        key.setResourceId(resourceId);
        OpResource record = (OpResource) getSqlMapClientTemplate().queryForObject("op_resource.abatorgenerated_selectByPrimaryKey",
                                                                                  key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public int deleteByExample(OpResourceExample example) {
        int rows = getSqlMapClientTemplate().delete("op_resource.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long resourceId) {
        OpResource key = new OpResource();
        key.setResourceId(resourceId);
        int rows = getSqlMapClientTemplate().delete("op_resource.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public int countByExample(OpResourceExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("op_resource.abatorgenerated_countByExample",
                                                                           example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public int updateByExampleSelective(OpResource record, OpResourceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_resource.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    public int updateByExample(OpResource record, OpResourceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_resource.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table op_resource
     * 
     * @abatorgenerated
     */
    private static class UpdateByExampleParms extends OpResourceExample {

        private Object record;

        public UpdateByExampleParms(Object record, OpResourceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    /*
     * (non-Javadoc)
     * @see com.gandalf.lottery.dao.OpResourceDAO#selectByPagination(com.gandalf.lottery.dao.entity.OpResourceExample)
     */
    @Override
    public PaginationQueryList<OpResource> selectByPagination(OpResourceExample example) {
        return getSqlMapClientTemplate().queryForPagination("op_resource.abatorgenerated_countByExample",
                                                            "op_resource.selectByPagination", example);
    }
}
