package com.gandalf.lottery.dao.impl;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.gandalf.framework.ibatis.GandalfSqlMapClientDaoSupport;
import com.gandalf.lottery.dao.OpRolePermissionDAO;
import com.gandalf.lottery.dao.entity.OpRolePermission;
import com.gandalf.lottery.dao.entity.OpRolePermissionExample;

@Repository
public class OpRolePermissionDAOImpl extends GandalfSqlMapClientDaoSupport implements OpRolePermissionDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    public OpRolePermissionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    public void insert(OpRolePermission record) {
        getSqlMapClientTemplate().insert("op_role_permission.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    public List selectByExample(OpRolePermissionExample example) {
        List list = getSqlMapClientTemplate().queryForList("op_role_permission.abatorgenerated_selectByExample",
                                                           example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    public int deleteByExample(OpRolePermissionExample example) {
        int rows = getSqlMapClientTemplate().delete("op_role_permission.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    public int countByExample(OpRolePermissionExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("op_role_permission.abatorgenerated_countByExample",
                                                                           example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    public int updateByExampleSelective(OpRolePermission record, OpRolePermissionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_role_permission.abatorgenerated_updateByExampleSelective",
                                                    parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    public int updateByExample(OpRolePermission record, OpRolePermissionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_role_permission.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table op_role_permission
     * 
     * @abatorgenerated
     */
    private static class UpdateByExampleParms extends OpRolePermissionExample {

        private Object record;

        public UpdateByExampleParms(Object record, OpRolePermissionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
