package com.gandalf.lottery.dao.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.jdbc.support.incrementer.DataFieldMaxValueIncrementer;
import org.springframework.stereotype.Repository;

import com.gandalf.framework.ibatis.GandalfSqlMapClientDaoSupport;
import com.gandalf.framework.ibatis.PaginationQueryList;
import com.gandalf.lottery.dao.OpRoleDAO;
import com.gandalf.lottery.dao.entity.OpRole;
import com.gandalf.lottery.dao.entity.OpRoleExample;

@Repository
public class OpRoleDAOImpl extends GandalfSqlMapClientDaoSupport implements OpRoleDAO {

    @Resource(name = "opRoleIncrementer")
    private DataFieldMaxValueIncrementer keyIncrementer;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public OpRoleDAOImpl() {
        super();
    }

    public void insert(OpRole record) {
        if (record.getRoleId() == null) {
            record.setRoleId(keyIncrementer.nextLongValue());
        }
        getSqlMapClientTemplate().insert("op_role.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public int updateByPrimaryKey(OpRole record) {
        int rows = getSqlMapClientTemplate().update("op_role.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(OpRole record) {
        int rows = getSqlMapClientTemplate().update("op_role.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public List selectByExample(OpRoleExample example) {
        List list = getSqlMapClientTemplate().queryForList("op_role.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public OpRole selectByPrimaryKey(Long roleId) {
        OpRole key = new OpRole();
        key.setRoleId(roleId);
        OpRole record = (OpRole) getSqlMapClientTemplate().queryForObject("op_role.abatorgenerated_selectByPrimaryKey",
                                                                          key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public int deleteByExample(OpRoleExample example) {
        int rows = getSqlMapClientTemplate().delete("op_role.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long roleId) {
        OpRole key = new OpRole();
        key.setRoleId(roleId);
        int rows = getSqlMapClientTemplate().delete("op_role.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public int countByExample(OpRoleExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("op_role.abatorgenerated_countByExample",
                                                                           example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public int updateByExampleSelective(OpRole record, OpRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_role.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    public int updateByExample(OpRole record, OpRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("op_role.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table op_role
     * 
     * @abatorgenerated
     */
    private static class UpdateByExampleParms extends OpRoleExample {

        private Object record;

        public UpdateByExampleParms(Object record, OpRoleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    /*
     * (non-Javadoc)
     * @see com.gandalf.lottery.dao.OpRoleDAO#selectByPagination(com.gandalf.lottery.dao.entity.OpRoleExample)
     */
    @Override
    public PaginationQueryList<OpRole> selectByPagination(OpRoleExample example) {
        return getSqlMapClientTemplate().queryForPagination("op_role.abatorgenerated_countByExample",
                                                            "op_role.selectByPagination", example);
    }
}
